import type { PRDSpec, GASFile } from '$lib/types';

export function generateGASFilesFromPRD(prd: PRDSpec): GASFile[] {
	const rawSheets = prd.sheets && prd.sheets.length > 0 ? prd.sheets : [
		{
			name: 'Data_Utama',
			description: 'Tabel data operasional utama',
			headers: ['ID', 'Tanggal', 'Nama', 'Kategori', 'Status', 'Catatan']
		},
		{
			name: 'Users',
			description: 'Tabel akun dan role pengguna sistem',
			headers: ['ID', 'Username', 'Password', 'NamaLengkap', 'Email', 'Role', 'Status', 'LastLogin', 'CreatedAt']
		},
		{
			name: 'Log_Aktivitas',
			description: 'Catatan riwayat audit dan log aktivitas',
			headers: ['Timestamp', 'Username', 'Aksi']
		}
	];

	// Clean sheet names and ensure valid structure
	const allSheets = rawSheets.map((s, idx) => ({
		name: (s.name || `Tabel_${idx + 1}`).trim().replace(/\s+/g, '_'),
		description: s.description || `Data ${s.name}`,
		headers: s.headers && s.headers.length > 0 ? s.headers : ['ID', 'Tanggal', 'Nama', 'Kategori', 'Status', 'Catatan']
	}));

	const hasUsersSheet = allSheets.some((s) => s.name.toLowerCase() === 'users' || s.name.toLowerCase() === 'user');
	const hasLogsSheet = allSheets.some((s) => s.name.toLowerCase().includes('log') || s.name.toLowerCase().includes('aktivitas'));

	// Find the primary operational sheet (e.g. Data_Utama or first non-users/non-log sheet)
	const operationalSheets = allSheets.filter(s => {
		const n = s.name.toLowerCase();
		return n !== 'users' && n !== 'user' && !n.includes('log');
	});

	const primarySheet = operationalSheets[0] || allSheets[0];
	const userSheetDef = allSheets.find(s => s.name.toLowerCase() === 'users' || s.name.toLowerCase() === 'user') || null;
	const logSheetDef = allSheets.find(s => s.name.toLowerCase().includes('log')) || null;

	// View Detection from PRD
	const allPrdViews = [
		...(prd.uiFeatures?.views || []).map(v => ({ title: v.title || '', desc: v.description || '', elements: v.elements || [] })),
		...(prd.uiUxSpec?.views || []).map(v => ({ title: v.title || '', desc: v.description || '', elements: v.features || [] }))
	];

	// Check if login view is explicitly specified in PRD
	const hasLoginView = Boolean(
		allPrdViews.some(v => {
			const t = v.title.toLowerCase();
			return t.includes('login') || t.includes('masuk') || t.includes('autentikasi') || t.includes('auth');
		}) ||
		prd.workflowSummary?.some(w => w.toLowerCase().includes('login') || w.toLowerCase().includes('masuk')) ||
		(hasUsersSheet && !prd.summary?.toLowerCase().includes('tanpa login'))
	);

	// Theme & Styling Detection from PRD
	const themeStr = `${prd.uiFeatures?.theme || ''} ${prd.uiUxSpec?.designSystem?.themeColor || ''} ${prd.uiUxSpec?.designSystem?.visualStyle || ''}`.toLowerCase();
	const isLightTheme = !themeStr.includes('dark') || themeStr.includes('light') || themeStr.includes('putih') || themeStr.includes('clean') || themeStr.includes('abu-abu lembut');
	const isBlueAccent = themeStr.includes('biru') || themeStr.includes('blue') || themeStr.includes('sky') || (!themeStr.includes('emerald') && !themeStr.includes('green'));

	const appNameEscaped = (prd.appName || 'Enterprise Web App').replace(/"/g, '\\"');
	const taglineEscaped = (prd.tagline || prd.summary || 'Enterprise Management Portal').replace(/"/g, '\\"');
	const spreadsheetNameEscaped = (prd.spreadsheetName || `DB - ${prd.appName || 'Enterprise App'}`).replace(/"/g, '\\"');
	const schemaJson = JSON.stringify(allSheets, null, 2);

	// 1. Manifest appsscript.json
	const appsscriptJson: GASFile = {
		name: 'appsscript',
		type: 'JSON',
		description: 'Google Apps Script Manifest & Web App Config',
		source: JSON.stringify(
			{
				timeZone: 'Asia/Jakarta',
				dependencies: {},
				exceptionLogging: 'STACKDRIVER',
				runtimeVersion: 'V8',
				webapp: {
					executeAs: 'USER_DEPLOYING',
					access: 'ANYONE'
				}
			},
			null,
			2
		)
	};

	// 2. Code.gs
	const codeGs: GASFile = {
		name: 'Code',
		type: 'SERVER_JS',
		description: 'Enterprise Multi-Sheet Backend RPC Engine, Auth, Activity Logger, and Full CRUD Handlers',
		source: `/**
 * ====================================================================
 * ${appNameEscaped} - Enterprise Backend Engine
 * Google Apps Script Multi-Table RPC Architecture
 * Generated by GAS Builder AI strictly adhering to PRD
 * ====================================================================
 */

const CONFIG = {
  APP_NAME: "${appNameEscaped}",
  SPREADSHEET_NAME: "${spreadsheetNameEscaped}",
  USERS_SHEET: "Users",
  LOGS_SHEET: "Log_Aktivitas",
  PRIMARY_SHEET: "${primarySheet.name}",
  SCHEMA: ${schemaJson}
};

/**
 * Handle HTTP GET - Serve Web App UI
 */
function doGet(e) {
  try {
    const template = HtmlService.createTemplateFromFile('index');
    template.appName = CONFIG.APP_NAME;
    template.hasAuth = ${hasLoginView ? 'true' : 'false'};

    return template
      .evaluate()
      .setTitle(CONFIG.APP_NAME)
      .addMetaTag('viewport', 'width=device-width, initial-scale=1')
      .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  } catch (err) {
    return HtmlService.createHtmlOutput('<h3>Error loading application: ' + err.toString() + '</h3>');
  }
}

/**
 * Get active database spreadsheet or create if not present
 */
function getSpreadsheet() {
  const files = DriveApp.getFilesByName(CONFIG.SPREADSHEET_NAME);
  if (files.hasNext()) {
    return SpreadsheetApp.open(files.next());
  }
  try {
    const active = SpreadsheetApp.getActiveSpreadsheet();
    if (active) return active;
  } catch (e) {}

  const newSheet = SpreadsheetApp.create(CONFIG.SPREADSHEET_NAME);
  initAllSheets(newSheet);
  return newSheet;
}

/**
 * Initialize All Defined Sheets & Header Styling
 */
function initAllSheets(ss) {
  CONFIG.SCHEMA.forEach(tableDef => {
    let sheet = ss.getSheetByName(tableDef.name);
    if (!sheet) {
      sheet = ss.insertSheet(tableDef.name);
    }
    const headerRange = sheet.getRange(1, 1, 1, tableDef.headers.length);
    headerRange.setValues([tableDef.headers]);
    headerRange.setFontWeight('bold');
    headerRange.setBackground('${isLightTheme ? '#1e293b' : '#0f172a'}');
    headerRange.setFontColor('${isBlueAccent ? '#38bdf8' : '#34d399'}');
  });

  const defaultSheet = ss.getSheetByName('Sheet1');
  if (defaultSheet && ss.getSheets().length > 1) {
    try { ss.deleteSheet(defaultSheet); } catch(e) {}
  }
}

/**
 * Helper: Record Activity Log
 */
function recordActivityLog(username, actionText) {
  try {
    const ss = getSpreadsheet();
    const logSheet = ss.getSheetByName(CONFIG.LOGS_SHEET);
    if (!logSheet) return;
    const nowStr = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm:ss');
    logSheet.appendRow([nowStr, username || 'System', actionText]);
  } catch(e) {
    Logger.log('Log error: ' + e.toString());
  }
}

/**
 * API: User Login Authentication & Session Token Generation
 */
function loginUser(username, password) {
  try {
    const ss = getSpreadsheet();
    let userSheet = ss.getSheetByName(CONFIG.USERS_SHEET);
    if (!userSheet) {
      initAllSheets(ss);
      userSheet = ss.getSheetByName(CONFIG.USERS_SHEET);
    }

    if (!userSheet) {
      if (username === 'admin' && password === 'admin123') {
        const adminUser = { userId: 'ADM-001', username: 'admin', name: 'Administrator Utama', email: 'admin@company.com', role: 'Admin', status: 'Active' };
        recordActivityLog('admin', 'Login berhasil sebagai Super Admin');
        return { success: true, user: adminUser, token: 'TOK-ADM-' + Date.now() };
      }
      return { success: false, error: 'Tabel pengguna belum siap' };
    }

    const data = userSheet.getDataRange().getValues();
    if (data.length <= 1) {
      if (username === 'admin' && password === 'admin123') {
        const adminUser = { userId: 'ADM-001', username: 'admin', name: 'Administrator Utama', email: 'admin@company.com', role: 'Admin', status: 'Active' };
        recordActivityLog('admin', 'Login berhasil sebagai Super Admin (Default)');
        return { success: true, user: adminUser, token: 'TOK-ADM-' + Date.now() };
      }
      return { success: false, error: 'Database pengguna kosong.' };
    }

    const headers = data[0].map(h => String(h).toLowerCase());
    const uIdx = headers.findIndex(h => h.includes('username') || h.includes('user') || h.includes('email'));
    const pIdx = headers.findIndex(h => h.includes('pass'));
    const nameIdx = headers.findIndex(h => h.includes('nama'));
    const emailIdx = headers.findIndex(h => h.includes('email'));
    const roleIdx = headers.findIndex(h => h.includes('role'));
    const statusIdx = headers.findIndex(h => h.includes('status'));
    const lastLoginIdx = headers.findIndex(h => h.includes('lastlogin') || h.includes('last_login'));

    for (let i = 1; i < data.length; i++) {
      const row = data[i];
      if (String(row[uIdx]).trim() === String(username).trim() && String(row[pIdx]) === String(password)) {
        if (statusIdx >= 0 && String(row[statusIdx]).toLowerCase() === 'inactive') {
          return { success: false, error: 'Akun ini telah dinonaktifkan oleh Admin.' };
        }

        const nowStr = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm:ss');
        if (lastLoginIdx >= 0) {
          userSheet.getRange(i + 1, lastLoginIdx + 1).setValue(nowStr);
        }

        const authenticatedUser = {
          userId: row[0] || 'USR-' + i,
          username: username,
          name: nameIdx >= 0 ? row[nameIdx] : username,
          email: emailIdx >= 0 ? row[emailIdx] : '',
          role: roleIdx >= 0 ? row[roleIdx] : 'User',
          status: statusIdx >= 0 ? row[statusIdx] : 'Active'
        };

        recordActivityLog(username, 'Login ke sistem (' + authenticatedUser.role + ')');
        return {
          success: true,
          user: authenticatedUser,
          token: 'TOK-' + username + '-' + Date.now()
        };
      }
    }

    return { success: false, error: 'Username atau password salah!' };
  } catch (err) {
    return { success: false, error: err.toString() };
  }
}

/**
 * API: Get Dashboard Enterprise Aggregate Stats & Status Breakdown
 */
function getDashboardStats() {
  try {
    const ss = getSpreadsheet();
    const stats = {};
    let totalAllRecords = 0;
    const tableSummaries = [];

    const statusCounts = { pending: 0, in_progress: 0, approved: 0, resolved: 0, rejected: 0, total: 0 };
    const categoryCounts = {};

    CONFIG.SCHEMA.forEach(tableDef => {
      let sheet = ss.getSheetByName(tableDef.name);
      if (!sheet) {
        initAllSheets(ss);
        sheet = ss.getSheetByName(tableDef.name);
      }
      const count = sheet ? Math.max(0, sheet.getLastRow() - 1) : 0;
      stats[tableDef.name] = count;
      totalAllRecords += count;

      tableSummaries.push({
        name: tableDef.name,
        description: tableDef.description,
        count: count,
        headersCount: tableDef.headers.length
      });

      // Status & Category aggregation on primary operational table
      if (tableDef.name === CONFIG.PRIMARY_SHEET && sheet && sheet.getLastRow() > 1) {
        const headers = tableDef.headers;
        const sIdx = headers.findIndex(h => h.toLowerCase().includes('status') || h.toLowerCase().includes('kondisi'));
        const kIdx = headers.findIndex(h => h.toLowerCase().includes('kategori') || h.toLowerCase().includes('tipe') || h.toLowerCase().includes('jenis'));
        
        const vals = sheet.getRange(2, 1, sheet.getLastRow() - 1, headers.length).getValues();
        statusCounts.total = vals.length;
        vals.forEach(r => {
          if (sIdx >= 0) {
            const s = String(r[sIdx]).toLowerCase();
            if (s.includes('pending') || s.includes('menunggu') || s.includes('open') || s.includes('baru')) statusCounts.pending++;
            else if (s.includes('progress') || s.includes('proses') || s.includes('review')) statusCounts.in_progress++;
            else if (s.includes('approved') || s.includes('disetujui') || s.includes('selesai') || s.includes('resolved') || s.includes('aktif')) statusCounts.approved++;
            else if (s.includes('rejected') || s.includes('ditolak') || s.includes('closed') || s.includes('batal')) statusCounts.rejected++;
          }
          if (kIdx >= 0) {
            const k = String(r[kIdx]).trim() || 'Umum';
            categoryCounts[k] = (categoryCounts[k] || 0) + 1;
          }
        });
      }
    });

    // Recent activity log from Log_Aktivitas or Primary Sheet
    const logSheet = ss.getSheetByName(CONFIG.LOGS_SHEET);
    let recentLogs = [];
    if (logSheet && logSheet.getLastRow() > 1) {
      const numRows = Math.min(6, logSheet.getLastRow() - 1);
      const startRow = Math.max(2, logSheet.getLastRow() - numRows + 1);
      const vals = logSheet.getRange(startRow, 1, numRows, 3).getValues();
      recentLogs = vals.reverse().map(r => {
        let ts = r[0];
        if (ts instanceof Date) ts = Utilities.formatDate(ts, Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm');
        return { timestamp: ts, username: r[1], action: r[2] };
      });
    }

    return {
      success: true,
      stats: stats,
      statusCounts: statusCounts,
      categoryCounts: categoryCounts,
      totalRecords: totalAllRecords,
      tables: tableSummaries,
      recentLogs: recentLogs,
      primarySheetName: CONFIG.PRIMARY_SHEET,
      spreadsheetUrl: ss.getUrl()
    };
  } catch (err) {
    return { success: false, error: err.toString() };
  }
}

/**
 * API: Get Data For Any Table Dynamically
 */
function getTableData(tableName) {
  try {
    const ss = getSpreadsheet();
    const tableDef = CONFIG.SCHEMA.find(t => t.name.toLowerCase() === String(tableName).toLowerCase()) || CONFIG.SCHEMA[0];
    let sheet = ss.getSheetByName(tableDef.name);
    if (!sheet) {
      initAllSheets(ss);
      sheet = ss.getSheetByName(tableDef.name);
    }

    const lastRow = sheet.getLastRow();
    if (lastRow <= 1) {
      return {
        success: true,
        tableName: tableDef.name,
        headers: tableDef.headers,
        rows: [],
        total: 0,
        spreadsheetUrl: ss.getUrl()
      };
    }

    const dataRange = sheet.getRange(2, 1, lastRow - 1, tableDef.headers.length);
    const rawValues = dataRange.getValues();

    const rows = rawValues.map((row, index) => {
      const item = { _rowIndex: index + 2 };
      tableDef.headers.forEach((header, colIdx) => {
        let val = row[colIdx];
        if (val instanceof Date) {
          val = Utilities.formatDate(val, Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm');
        }
        item[header] = val;
      });
      return item;
    });

    return {
      success: true,
      tableName: tableDef.name,
      headers: tableDef.headers,
      rows: rows,
      total: rows.length,
      spreadsheetUrl: ss.getUrl()
    };
  } catch (err) {
    return { success: false, error: err.toString() };
  }
}

/**
 * API: Create Record in Any Target Table
 */
function createRecord(tableName, payload, currentUser) {
  try {
    const ss = getSpreadsheet();
    const tableDef = CONFIG.SCHEMA.find(t => t.name.toLowerCase() === String(tableName).toLowerCase()) || CONFIG.SCHEMA[0];
    let sheet = ss.getSheetByName(tableDef.name);
    if (!sheet) {
      initAllSheets(ss);
      sheet = ss.getSheetByName(tableDef.name);
    }

    const prefix = tableDef.name.substring(0, 3).toUpperCase();
    const newId = prefix + '-' + Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyMM') + '-' + Math.floor(1000 + Math.random() * 9000);
    const nowStr = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm:ss');

    const rowData = tableDef.headers.map(header => {
      const hLower = header.toLowerCase();
      if ((hLower.includes('id') || hLower.includes('kode')) && !payload[header] && !payload[hLower]) return newId;
      if ((hLower.includes('tanggal') || hLower.includes('createdat') || hLower === 'timestamp') && !payload[header] && !payload[hLower]) {
        return nowStr;
      }
      return payload[header] !== undefined ? payload[header] : (payload[hLower] !== undefined ? payload[hLower] : '');
    });

    sheet.appendRow(rowData);
    recordActivityLog(currentUser || 'Admin', 'Menambah data baru di tabel ' + tableDef.name + ' (' + newId + ')');
    return { success: true, message: 'Data berhasil disimpan ke tabel ' + tableDef.name + '!', id: newId };
  } catch (err) {
    return { success: false, error: err.toString() };
  }
}

/**
 * API: Update Record in Target Table
 */
function updateRecord(tableName, id, updates, currentUser) {
  try {
    const ss = getSpreadsheet();
    const tableDef = CONFIG.SCHEMA.find(t => t.name.toLowerCase() === String(tableName).toLowerCase()) || CONFIG.SCHEMA[0];
    const sheet = ss.getSheetByName(tableDef.name);
    if (!sheet) throw new Error('Sheet ' + tableName + ' tidak ditemukan');

    const lastRow = sheet.getLastRow();
    if (lastRow <= 1) throw new Error('Tabel ' + tableName + ' masih kosong');

    const data = sheet.getRange(2, 1, lastRow - 1, tableDef.headers.length).getValues();
    const idColIdx = tableDef.headers.findIndex(h => h.toLowerCase().includes('id') || h.toLowerCase().includes('kode'));
    const targetIdx = idColIdx >= 0 ? idColIdx : 0;

    let targetRow = -1;
    for (let i = 0; i < data.length; i++) {
      if (String(data[i][targetIdx]) === String(id)) {
        targetRow = i + 2;
        break;
      }
    }

    if (targetRow === -1) throw new Error('Data dengan ID ' + id + ' tidak ditemukan');

    tableDef.headers.forEach((header, colIdx) => {
      if (updates[header] !== undefined) {
        sheet.getRange(targetRow, colIdx + 1).setValue(updates[header]);
      }
    });

    recordActivityLog(currentUser || 'Admin', 'Memperbarui data di ' + tableDef.name + ' (' + id + ')');
    return { success: true, message: 'Data berhasil diperbarui!' };
  } catch (err) {
    return { success: false, error: err.toString() };
  }
}

/**
 * API: Delete Record from Target Table
 */
function deleteRecord(tableName, id, currentUser) {
  try {
    const ss = getSpreadsheet();
    const tableDef = CONFIG.SCHEMA.find(t => t.name.toLowerCase() === String(tableName).toLowerCase()) || CONFIG.SCHEMA[0];
    const sheet = ss.getSheetByName(tableDef.name);
    if (!sheet) throw new Error('Sheet ' + tableName + ' tidak ditemukan');

    const lastRow = sheet.getLastRow();
    if (lastRow <= 1) throw new Error('Tabel kosong');

    const data = sheet.getRange(2, 1, lastRow - 1, tableDef.headers.length).getValues();
    const idColIdx = tableDef.headers.findIndex(h => h.toLowerCase().includes('id') || h.toLowerCase().includes('kode'));
    const targetIdx = idColIdx >= 0 ? idColIdx : 0;

    for (let i = 0; i < data.length; i++) {
      if (String(data[i][targetIdx]) === String(id)) {
        sheet.deleteRow(i + 2);
        recordActivityLog(currentUser || 'Admin', 'Menghapus data di ' + tableDef.name + ' (' + id + ')');
        return { success: true, message: 'Data berhasil dihapus!' };
      }
    }

    return { success: false, error: 'Data dengan ID ' + id + ' tidak ditemukan' };
  } catch (err) {
    return { success: false, error: err.toString() };
  }
}
`
	};

	// 3. Setup.gs
	const setupGs: GASFile = {
		name: 'Setup',
		type: 'SERVER_JS',
		description: 'Automated Multi-Table Enterprise Setup & Sample Data Seeder (Phase 5)',
		source: `/**
 * ====================================================================
 * Enterprise Automated Setup & Seeder Script (Phase 5)
 * ====================================================================
 */
function initialSetup() {
  Logger.log('Memulai Setup Database Enterprise untuk ' + CONFIG.APP_NAME + '...');
  const ss = getSpreadsheet();
  initAllSheets(ss);

  // 1. Seed Users
  const userSheet = ss.getSheetByName(CONFIG.USERS_SHEET);
  if (userSheet && userSheet.getLastRow() <= 1) {
    Logger.log('Mengisi data awal untuk tabel Users...');
    createRecord(CONFIG.USERS_SHEET, {
      ID: 'USR-001',
      Username: 'admin',
      Password: 'admin123',
      NamaLengkap: 'Administrator Utama',
      Email: 'admin@company.com',
      Role: 'Admin',
      Status: 'Active',
      LastLogin: '2026-09-12 10:00:00',
      CreatedAt: '2026-09-01 08:00:00'
    }, 'System');

    createRecord(CONFIG.USERS_SHEET, {
      ID: 'USR-002',
      Username: 'budi',
      Password: 'budi123',
      NamaLengkap: 'Budi Santoso',
      Email: 'budi@company.com',
      Role: 'User',
      Status: 'Active',
      LastLogin: '2026-09-12 09:30:00',
      CreatedAt: '2026-09-02 08:00:00'
    }, 'System');
  }

  // 2. Seed Data_Utama
  const primarySheet = ss.getSheetByName(CONFIG.PRIMARY_SHEET);
  if (primarySheet && primarySheet.getLastRow() <= 1) {
    Logger.log('Mengisi data awal untuk tabel ' + CONFIG.PRIMARY_SHEET + '...');
    createRecord(CONFIG.PRIMARY_SHEET, {
      ID: 'DAT-001',
      Tanggal: '2026-09-12 10:15',
      Nama: 'Permohonan Lisensi Software Tim Dev',
      Kategori: 'Software & Tools',
      Status: 'Approved',
      Catatan: 'Lisensi IDE telah disetujui untuk 5 developer'
    }, 'System');

    createRecord(CONFIG.PRIMARY_SHEET, {
      ID: 'DAT-002',
      Tanggal: '2026-09-12 11:30',
      Nama: 'Pengadaan Hardware Server Backup',
      Kategori: 'Hardware & Server',
      Status: 'In Progress',
      Catatan: 'Sedang proses verifikasi vendor penyedia'
    }, 'System');

    createRecord(CONFIG.PRIMARY_SHEET, {
      ID: 'DAT-003',
      Tanggal: '2026-09-12 13:00',
      Nama: 'Audit Keamanan Jaringan Kantor Pusat',
      Kategori: 'Security & Network',
      Status: 'Pending',
      Catatan: 'Menunggu persetujuan jadwal audit dari IT Security'
    }, 'System');
  }

  // 3. Seed Log_Aktivitas
  const logSheet = ss.getSheetByName(CONFIG.LOGS_SHEET);
  if (logSheet && logSheet.getLastRow() <= 1) {
    Logger.log('Mengisi log awal sistem...');
    recordActivityLog('System', 'Inisialisasi database dan setup multi-tabel berhasil');
  }

  Logger.log('Setup Selesai! Semua tabel siap di: ' + ss.getUrl());
}
`
	};

	// 4. index.html - Multi-View Enterprise SPA strictly matching PRD Views
	const bgClass = isLightTheme ? 'bg-slate-50 text-slate-800' : 'bg-[#0b0f19] text-slate-100';
	const cardClass = isLightTheme ? 'bg-white border-slate-200 shadow-sm' : 'glass-card border-slate-800 shadow-xl';
	const sidebarClass = isLightTheme ? 'bg-white border-r border-slate-200 shadow-sm' : 'glass-sidebar';
	const headerClass = isLightTheme ? 'bg-white/95 border-b border-slate-200 text-slate-800' : 'bg-slate-900/80 border-b border-slate-800 text-slate-100';
	const inputClass = isLightTheme ? 'bg-slate-50 border border-slate-300 text-slate-900 focus:border-blue-500' : 'bg-slate-900 border border-slate-700 text-white focus:border-emerald-500';

	const indexHtml: GASFile = {
		name: 'index',
		type: 'HTML',
		description: 'Enterprise Web App Layout matching PRD UI, Authentication, and Views specifications',
		source: `<!DOCTYPE html>
<html lang="id" class="${isLightTheme ? 'light' : 'dark'}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${appNameEscaped}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'Plus Jakarta Sans', sans-serif; }
    .glass-card { background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.08); }
    .glass-sidebar { background: rgba(15, 23, 42, 0.96); backdrop-filter: blur(16px); border-right: 1px solid rgba(255, 255, 255, 0.08); }
    .custom-scrollbar::-webkit-scrollbar { width: 6px; height: 6px; }
    .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(150,150,150,0.25); border-radius: 9999px; }
  </style>
</head>
<body class="${bgClass} min-h-screen flex flex-col selection:bg-blue-500/20 selection:text-blue-600">

  ${hasLoginView ? `<!-- ========================================== -->
  <!-- 1. VIEW PRD: LAYAR LOGIN                   -->
  <!-- ========================================== -->
  <div id="view-login" class="view-screen min-h-screen flex items-center justify-center p-4">
    <div class="${cardClass} rounded-3xl p-8 border w-full max-w-md space-y-6 relative">
      <div class="text-center space-y-2">
        <div class="w-14 h-14 rounded-2xl bg-gradient-to-tr from-blue-600 to-sky-400 flex items-center justify-center mx-auto text-white font-bold text-2xl shadow-lg shadow-blue-500/25">
          <i class="fa-solid fa-shield-halved"></i>
        </div>
        <h2 class="text-xl font-extrabold tracking-tight ${isLightTheme ? 'text-slate-900' : 'text-white'}">${appNameEscaped}</h2>
        <p class="text-xs ${isLightTheme ? 'text-slate-500' : 'text-slate-400'}">${taglineEscaped}</p>
      </div>

      <div id="login-error" class="hidden p-3 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-600 text-xs flex items-center gap-2">
        <i class="fa-solid fa-triangle-exclamation text-rose-500"></i>
        <span id="login-error-text">Username atau password salah</span>
      </div>

      <form onsubmit="handleLogin(event)" class="space-y-4">
        <div>
          <label class="block text-xs font-semibold ${isLightTheme ? 'text-slate-700' : 'text-slate-300'} mb-1.5">Username / Email</label>
          <div class="relative">
            <i class="fa-solid fa-user absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 text-xs"></i>
            <input type="text" id="login-username" required placeholder="admin" value="admin" class="w-full pl-9 pr-4 py-2.5 rounded-xl text-xs ${inputClass}">
          </div>
        </div>

        <div>
          <label class="block text-xs font-semibold ${isLightTheme ? 'text-slate-700' : 'text-slate-300'} mb-1.5">Password</label>
          <div class="relative">
            <i class="fa-solid fa-lock absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 text-xs"></i>
            <input type="password" id="login-password" required placeholder="admin123" value="admin123" class="w-full pl-9 pr-4 py-2.5 rounded-xl text-xs ${inputClass}">
          </div>
        </div>

        <button type="submit" id="btn-login" class="w-full py-3 bg-gradient-to-r from-blue-600 to-sky-500 hover:from-blue-500 hover:to-sky-400 text-white font-bold rounded-xl text-xs shadow-lg shadow-blue-500/25 transition transform active:scale-95 flex items-center justify-center gap-2">
          <span>Masuk ke Sistem</span>
          <i class="fa-solid fa-arrow-right"></i>
        </button>
      </form>

      <div class="p-3 rounded-xl ${isLightTheme ? 'bg-slate-100 text-slate-600' : 'bg-slate-900/60 text-slate-400'} border border-slate-200/60 text-[11px] text-center space-y-1">
        <p>Akun Demo: <strong>admin</strong> (pass: <code>admin123</code>) • <strong>budi</strong> (pass: <code>budi123</code>)</p>
      </div>
    </div>
  </div>` : ''}

  <!-- ========================================== -->
  <!-- 2. ENTERPRISE APP SHELL                    -->
  <!-- ========================================== -->
  <div id="view-dashboard-shell" class="view-screen ${hasLoginView ? 'hidden' : ''} flex-1 flex flex-row min-h-screen">

    <!-- ENTERPRISE SIDEBAR NAVIGATION (Matching PRD Views) -->
    <aside id="app-sidebar" class="${sidebarClass} w-64 shrink-0 flex flex-col justify-between hidden md:flex transition-all duration-300 z-40 fixed md:static inset-y-0 left-0">
      <div class="p-4 space-y-5 overflow-y-auto custom-scrollbar flex-1">
        <!-- Brand Header -->
        <div class="flex items-center justify-between pb-3 border-b ${isLightTheme ? 'border-slate-200' : 'border-slate-800'}">
          <div class="flex items-center space-x-3">
            <div class="w-9 h-9 rounded-xl bg-gradient-to-tr from-blue-600 to-sky-400 flex items-center justify-center shadow-lg shadow-blue-500/20 text-white font-bold">
              <i class="fa-solid fa-shield-halved text-base"></i>
            </div>
            <div>
              <h2 class="text-xs font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'} tracking-tight truncate max-w-[130px]">${appNameEscaped}</h2>
              <span class="text-[10px] text-blue-500 font-semibold flex items-center gap-1">
                <span class="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse"></span> Enterprise Suite
              </span>
            </div>
          </div>
          <button onclick="toggleSidebar()" class="md:hidden text-slate-400 hover:text-slate-600 p-1">
            <i class="fa-solid fa-xmark"></i>
          </button>
        </div>

        <!-- Section 1: Dashboard View -->
        <div class="space-y-1">
          <p class="px-2.5 text-[10px] font-bold text-slate-400 uppercase tracking-wider">Navigasi Utama</p>
          <button onclick="switchView('dashboard')" id="nav-dashboard" class="sidebar-nav-btn active w-full flex items-center gap-3 px-3 py-2.5 rounded-xl bg-blue-500/10 text-blue-600 font-semibold text-xs border border-blue-500/20 transition">
            <i class="fa-solid fa-chart-pie w-4 text-center"></i>
            <span>Dashboard Utama</span>
          </button>
        </div>

        <!-- Section 2: Data Utama / Status Tracker -->
        <div class="space-y-1 pt-2">
          <p class="px-2.5 text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center justify-between">
            <span>Data & Operasional</span>
            <span id="sidebar-badge-data-utama" class="text-[9px] ${isLightTheme ? 'bg-slate-100 text-slate-600' : 'bg-slate-800 text-slate-400'} px-1.5 py-0.5 rounded font-mono">0</span>
          </p>
          <button onclick="switchView('data_utama')" id="nav-data_utama" class="sidebar-nav-btn w-full flex items-center gap-2.5 px-3 py-2 rounded-xl text-slate-500 hover:text-blue-600 hover:bg-blue-50/60 font-medium text-xs transition">
            <i class="fa-solid fa-table-list w-4 text-center text-blue-500"></i>
            <span>Tabel & Tracker</span>
          </button>
        </div>

        <!-- Section 3: Admin Only Modules -->
        <div class="space-y-1 pt-2" id="sidebar-admin-section">
          <p class="px-2.5 text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center justify-between">
            <span>Admin Control</span>
            <span class="text-[9px] bg-indigo-500/10 text-indigo-500 px-1.5 py-0.5 rounded font-bold">Admin</span>
          </p>
          ${hasUsersSheet ? `
          <button onclick="switchView('manajemen_user')" id="nav-manajemen_user" class="sidebar-nav-btn w-full flex items-center gap-2.5 px-3 py-2 rounded-xl text-slate-500 hover:text-blue-600 hover:bg-blue-50/60 font-medium text-xs transition">
            <i class="fa-solid fa-users-gear w-4 text-center text-indigo-500"></i>
            <span>Manajemen User</span>
          </button>` : ''}
          ${hasLogsSheet ? `
          <button onclick="switchView('log_aktivitas')" id="nav-log_aktivitas" class="sidebar-nav-btn w-full flex items-center gap-2.5 px-3 py-2 rounded-xl text-slate-500 hover:text-blue-600 hover:bg-blue-50/60 font-medium text-xs transition">
            <i class="fa-solid fa-clock-rotate-left w-4 text-center text-cyan-500"></i>
            <span>Log Aktivitas</span>
          </button>` : ''}
        </div>

        <!-- Section 4: Google Sheets DB Link -->
        <div class="space-y-1 pt-2">
          <p class="px-2.5 text-[10px] font-bold text-slate-400 uppercase tracking-wider">Database</p>
          <a id="sidebar-sheet-link" href="#" target="_blank" class="w-full flex items-center gap-2.5 px-3 py-2 rounded-xl text-slate-500 hover:text-emerald-600 hover:bg-emerald-50/60 font-medium text-xs transition">
            <i class="fa-solid fa-file-excel w-4 text-center text-emerald-500"></i>
            <span>Buka Google Sheets</span>
          </a>
        </div>
      </div>

      <!-- Bottom Profile Mini Card in Sidebar -->
      <div class="p-3.5 border-t ${isLightTheme ? 'border-slate-200 bg-slate-50' : 'border-slate-800 bg-slate-950/50'}">
        <div class="flex items-center justify-between">
          <div class="flex items-center space-x-2.5 overflow-hidden">
            <div class="w-8 h-8 rounded-full bg-blue-500/10 border border-blue-500/30 text-blue-600 font-bold text-xs flex items-center justify-center shrink-0">
              <span id="sidebar-user-initial">A</span>
            </div>
            <div class="overflow-hidden">
              <p id="sidebar-user-name" class="text-xs font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'} truncate">Administrator Utama</p>
              <p id="sidebar-user-role" class="text-[10px] text-blue-500 font-semibold truncate">Role: Admin</p>
            </div>
          </div>
          <button onclick="handleLogout()" title="Keluar / Logout" class="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition shrink-0">
            <i class="fa-solid fa-right-from-bracket text-xs"></i>
          </button>
        </div>
      </div>
    </aside>

    <!-- MAIN RIGHT CONTENT WRAPPER -->
    <div class="flex-1 flex flex-col min-w-0">

      <!-- TOPBAR NAVBAR -->
      <header class="${headerClass} sticky top-0 z-30 px-4 sm:px-6 h-16 flex items-center justify-between backdrop-blur">
        <div class="flex items-center space-x-3">
          <button onclick="toggleSidebar()" class="md:hidden p-2 rounded-xl ${isLightTheme ? 'bg-slate-100 text-slate-700' : 'bg-slate-800 text-slate-300'} border border-slate-200">
            <i class="fa-solid fa-bars"></i>
          </button>
          <div>
            <h1 id="topbar-page-title" class="text-sm font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'} tracking-tight">Dashboard Utama</h1>
            <p id="topbar-page-subtitle" class="text-[11px] text-slate-400">${appNameEscaped}</p>
          </div>
        </div>

        <!-- Right: Actions & User Dropdown -->
        <div class="flex items-center space-x-2.5">
          <button onclick="reloadCurrentView()" id="btn-refresh" class="px-3 py-1.5 rounded-xl ${isLightTheme ? 'bg-slate-100 hover:bg-slate-200 text-slate-700' : 'bg-slate-800 hover:bg-slate-700 text-slate-300'} text-xs font-semibold flex items-center gap-1.5 border border-slate-200 transition">
            <i class="fa-solid fa-rotate-right" id="refresh-icon"></i> <span class="hidden sm:inline">Refresh</span>
          </button>
          
          <button onclick="openCreateModalForActiveView()" id="btn-topbar-add" class="hidden px-3.5 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-lg shadow-blue-500/20 transition transform active:scale-95">
            <i class="fa-solid fa-plus"></i> <span id="btn-topbar-add-label">Tambah Data</span>
          </button>

          <!-- User Profile & Logout Dropdown -->
          <div class="relative">
            <button onclick="toggleProfileDropdown()" id="btn-profile-dropdown" class="flex items-center space-x-2 p-1.5 rounded-xl ${isLightTheme ? 'bg-slate-100 hover:bg-slate-200' : 'bg-slate-800 hover:bg-slate-700'} border border-slate-200 transition">
              <div class="w-7 h-7 rounded-lg bg-blue-500/10 text-blue-600 font-bold text-xs flex items-center justify-center">
                <span id="topbar-user-initial">A</span>
              </div>
              <span id="topbar-user-name" class="text-xs font-semibold ${isLightTheme ? 'text-slate-800' : 'text-white'} hidden sm:inline max-w-[120px] truncate">Admin</span>
              <i class="fa-solid fa-chevron-down text-[10px] text-slate-400"></i>
            </button>

            <!-- Dropdown Menu Box -->
            <div id="profile-dropdown" class="hidden absolute right-0 mt-2 w-56 rounded-2xl ${cardClass} shadow-2xl p-2 space-y-1 z-50">
              <div class="px-3 py-2 border-b ${isLightTheme ? 'border-slate-100' : 'border-slate-800'} mb-1">
                <p id="dropdown-user-name" class="text-xs font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'} truncate">Administrator Utama</p>
                <p id="dropdown-user-role" class="text-[10px] text-blue-500 font-semibold">Role: Admin</p>
              </div>
              <button onclick="handleLogout()" class="w-full text-left px-3 py-2 rounded-xl text-xs text-rose-600 hover:bg-rose-50 flex items-center gap-2.5 transition">
                <i class="fa-solid fa-right-from-bracket"></i>
                <span>Keluar / Logout</span>
              </button>
            </div>
          </div>
        </div>
      </header>

      <!-- MAIN DYNAMIC CONTENT CONTAINER -->
      <main class="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">

        <!-- ============================================== -->
        <!-- VIEW 2: DASHBOARD UTAMA (PRD Spec)             -->
        <!-- ============================================== -->
        <div id="subview-dashboard" class="space-y-6">
          <!-- Hero Banner -->
          <div class="${cardClass} rounded-3xl p-6 border relative overflow-hidden bg-gradient-to-r from-blue-600 via-indigo-600 to-blue-700 text-white shadow-xl">
            <div class="relative z-10 max-w-2xl space-y-2">
              <span class="px-2.5 py-1 rounded-full bg-white/20 backdrop-blur text-white text-[11px] font-semibold">Enterprise System</span>
              <h2 class="text-xl sm:text-2xl font-black tracking-tight">${appNameEscaped}</h2>
              <p class="text-xs text-blue-100">${taglineEscaped}</p>
            </div>
            <div class="absolute -right-6 -bottom-6 opacity-15 text-white text-9xl">
              <i class="fa-solid fa-shield-halved"></i>
            </div>
          </div>

          <!-- KPI Stats Breakdown -->
          <div>
            <h3 class="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">Ringkasan Data & Status</h3>
            <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
              <!-- Total Records -->
              <div class="${cardClass} rounded-2xl p-4 border flex items-center justify-between">
                <div>
                  <p class="text-[11px] font-semibold text-slate-400 uppercase">Total Data Utama</p>
                  <h4 id="stat-total-records" class="text-2xl font-black ${isLightTheme ? 'text-slate-900' : 'text-white'} mt-0.5">0</h4>
                </div>
                <div class="w-10 h-10 rounded-xl bg-blue-500/10 text-blue-600 flex items-center justify-center text-base">
                  <i class="fa-solid fa-layer-group"></i>
                </div>
              </div>

              <!-- Pending Review -->
              <div class="${cardClass} rounded-2xl p-4 border flex items-center justify-between">
                <div>
                  <p class="text-[11px] font-semibold text-amber-500 uppercase">Pending / Review</p>
                  <h4 id="stat-pending-records" class="text-2xl font-black text-amber-500 mt-0.5">0</h4>
                </div>
                <div class="w-10 h-10 rounded-xl bg-amber-500/10 text-amber-600 flex items-center justify-center text-base">
                  <i class="fa-solid fa-clock"></i>
                </div>
              </div>

              <!-- Approved / Selesai -->
              <div class="${cardClass} rounded-2xl p-4 border flex items-center justify-between">
                <div>
                  <p class="text-[11px] font-semibold text-emerald-500 uppercase">Disetujui / Selesai</p>
                  <h4 id="stat-approved-records" class="text-2xl font-black text-emerald-500 mt-0.5">0</h4>
                </div>
                <div class="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-600 flex items-center justify-center text-base">
                  <i class="fa-solid fa-circle-check"></i>
                </div>
              </div>

              <!-- Total Users -->
              <div class="${cardClass} rounded-2xl p-4 border flex items-center justify-between">
                <div>
                  <p class="text-[11px] font-semibold text-indigo-500 uppercase">Total Pengguna</p>
                  <h4 id="stat-total-users" class="text-2xl font-black text-indigo-500 mt-0.5">0</h4>
                </div>
                <div class="w-10 h-10 rounded-xl bg-indigo-500/10 text-indigo-600 flex items-center justify-center text-base">
                  <i class="fa-solid fa-users"></i>
                </div>
              </div>
            </div>
          </div>

          <!-- Charts Grid -->
          <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div class="${cardClass} rounded-2xl p-5 border space-y-3">
              <div class="flex items-center justify-between">
                <h4 class="text-xs font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'}">Distribusi Kategori</h4>
                <span class="text-xs text-blue-500 font-semibold"><i class="fa-solid fa-chart-pie"></i> Chart</span>
              </div>
              <div class="h-56 relative flex items-center justify-center">
                <canvas id="chartCategoryCanvas"></canvas>
              </div>
            </div>

            <div class="${cardClass} rounded-2xl p-5 border space-y-3">
              <div class="flex items-center justify-between">
                <h4 class="text-xs font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'}">Aktivitas 7 Hari Terakhir</h4>
                <span class="text-xs text-blue-500 font-semibold"><i class="fa-solid fa-chart-line"></i> Tren</span>
              </div>
              <div class="h-56 relative flex items-center justify-center">
                <canvas id="chartTrendCanvas"></canvas>
              </div>
            </div>
          </div>

          <!-- Recent Audit Logs Feed -->
          <div class="${cardClass} rounded-2xl border p-5 space-y-4">
            <div class="flex items-center justify-between">
              <div>
                <h4 class="text-xs font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'}">Aktivitas Sistem Terbaru</h4>
                <p class="text-[11px] text-slate-400">Riwayat audit log dan interaksi user</p>
              </div>
              <button onclick="switchView('log_aktivitas')" class="text-xs text-blue-600 hover:underline font-semibold">Buka Semua Log &rarr;</button>
            </div>
            <div class="overflow-x-auto">
              <table class="w-full text-left border-collapse text-xs">
                <thead>
                  <tr class="border-b ${isLightTheme ? 'border-slate-100 text-slate-500' : 'border-slate-800 text-slate-400'} font-semibold">
                    <th class="py-2.5 px-3">Waktu</th>
                    <th class="py-2.5 px-3">User</th>
                    <th class="py-2.5 px-3">Aksi / Aktivitas</th>
                  </tr>
                </thead>
                <tbody id="recent-logs-tbody" class="divide-y ${isLightTheme ? 'divide-slate-100 text-slate-700' : 'divide-slate-800/60 text-slate-200'}"></tbody>
              </table>
            </div>
          </div>
        </div>

        <!-- ============================================== -->
        <!-- VIEW 3: TABEL & STATUS TRACKER (Data_Utama)     -->
        <!-- ============================================== -->
        <div id="subview-data_utama" class="hidden space-y-5">
          <div class="${cardClass} rounded-2xl border p-5 space-y-4">
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div class="flex items-center gap-2">
                  <h3 class="text-base font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'}">Tabel Data Utama & Status Tracker</h3>
                  <span id="data_utama-count-badge" class="px-2 py-0.5 rounded-full bg-blue-500/10 text-blue-600 text-xs font-bold border border-blue-500/20">0 Baris</span>
                </div>
                <p class="text-xs text-slate-400 mt-0.5">Kelola entri data operasional dan pantau status pengerjaan</p>
              </div>

              <div class="flex items-center space-x-2">
                <button onclick="exportTableToCSV('Data_Utama')" class="px-3 py-2 ${isLightTheme ? 'bg-slate-100 hover:bg-slate-200 text-slate-700' : 'bg-slate-800 hover:bg-slate-700 text-slate-300'} rounded-xl text-xs font-medium border border-slate-200 transition flex items-center gap-1.5">
                  <i class="fa-solid fa-download"></i> <span class="hidden sm:inline">Export CSV</span>
                </button>
                <button onclick="openCreateModal('Data_Utama')" class="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl text-xs shadow-lg shadow-blue-500/20 transition flex items-center gap-1.5 transform active:scale-95">
                  <i class="fa-solid fa-plus"></i> <span>Tambah Data</span>
                </button>
              </div>
            </div>

            <div class="flex flex-col sm:flex-row items-center gap-3 pt-2 border-t ${isLightTheme ? 'border-slate-100' : 'border-slate-800/80'}">
              <div class="relative flex-1 w-full">
                <i class="fa-solid fa-magnifying-glass absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 text-xs"></i>
                <input type="text" id="data_utama-search" onkeyup="filterDataUtamaTable()" placeholder="Cari data utama..." class="w-full pl-9 pr-4 py-2 rounded-xl text-xs ${inputClass} transition">
              </div>
              <select id="data_utama-filter-status" onchange="filterDataUtamaTable()" class="px-3 py-2 rounded-xl text-xs ${inputClass}">
                <option value="ALL">Semua Status</option>
                <option value="Pending">Pending / Review</option>
                <option value="In Progress">In Progress</option>
                <option value="Approved">Approved / Selesai</option>
                <option value="Rejected">Rejected</option>
              </select>
            </div>
          </div>

          <div class="${cardClass} rounded-2xl border overflow-hidden">
            <div class="overflow-x-auto min-h-[300px] relative">
              <table class="w-full text-left border-collapse">
                <thead>
                  <tr class="border-b ${isLightTheme ? 'border-slate-200 bg-slate-50 text-slate-600' : 'border-slate-800 bg-slate-900/60 text-slate-400'} text-[11px] font-semibold uppercase tracking-wider">
                    <th class="py-3 px-4">ID</th>
                    <th class="py-3 px-4">Tanggal</th>
                    <th class="py-3 px-4">Nama</th>
                    <th class="py-3 px-4">Kategori</th>
                    <th class="py-3 px-4">Status</th>
                    <th class="py-3 px-4">Catatan</th>
                    <th class="py-3 px-4 text-right">Aksi</th>
                  </tr>
                </thead>
                <tbody id="data_utama-tbody" class="divide-y ${isLightTheme ? 'divide-slate-100 text-slate-700' : 'divide-slate-800/60 text-slate-200'} text-xs"></tbody>
              </table>
              <div id="data_utama-empty" class="hidden py-12 text-center text-xs text-slate-400">Belum ada data utama</div>
            </div>
          </div>
        </div>

        <!-- ============================================== -->
        <!-- VIEW 4: MANAJEMEN USER (Admin Only) (PRD Spec) -->
        <!-- ============================================== -->
        <div id="subview-manajemen_user" class="hidden space-y-5">
          <div class="${cardClass} rounded-2xl border p-5 space-y-4">
            <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div class="flex items-center gap-2">
                  <h3 class="text-base font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'}">Manajemen Akun Pengguna</h3>
                  <span class="px-2 py-0.5 rounded-full bg-indigo-500/10 text-indigo-500 text-xs font-bold border border-indigo-500/20">Khusus Admin</span>
                </div>
                <p class="text-xs text-slate-400 mt-0.5">Kelola kredensial akun, hak akses role (Admin/User), dan status aktifasi pengguna</p>
              </div>

              <div class="flex items-center space-x-2">
                <button onclick="openCreateModal('Users')" class="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs shadow-lg shadow-indigo-500/20 transition flex items-center gap-1.5 transform active:scale-95">
                  <i class="fa-solid fa-user-plus"></i> <span>Tambah User Baru</span>
                </button>
              </div>
            </div>

            <div class="flex flex-col sm:flex-row items-center gap-3 pt-2 border-t ${isLightTheme ? 'border-slate-100' : 'border-slate-800/80'}">
              <div class="relative flex-1 w-full">
                <i class="fa-solid fa-magnifying-glass absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 text-xs"></i>
                <input type="text" id="users-search" onkeyup="filterUsersTable()" placeholder="Cari username, nama, atau email..." class="w-full pl-9 pr-4 py-2 rounded-xl text-xs ${inputClass} transition">
              </div>
            </div>
          </div>

          <div class="${cardClass} rounded-2xl border overflow-hidden">
            <div class="overflow-x-auto min-h-[250px]">
              <table class="w-full text-left border-collapse">
                <thead>
                  <tr class="border-b ${isLightTheme ? 'border-slate-200 bg-slate-50 text-slate-600' : 'border-slate-800 bg-slate-900/60 text-slate-400'} text-[11px] font-semibold uppercase tracking-wider">
                    <th class="py-3 px-4">User ID</th>
                    <th class="py-3 px-4">Username</th>
                    <th class="py-3 px-4">Nama Lengkap</th>
                    <th class="py-3 px-4">Email</th>
                    <th class="py-3 px-4">Role</th>
                    <th class="py-3 px-4">Status</th>
                    <th class="py-3 px-4">Last Login</th>
                    <th class="py-3 px-4 text-right">Aksi</th>
                  </tr>
                </thead>
                <tbody id="users-tbody" class="divide-y ${isLightTheme ? 'divide-slate-100 text-slate-700' : 'divide-slate-800/60 text-slate-200'} text-xs"></tbody>
              </table>
            </div>
          </div>
        </div>

        <!-- ============================================== -->
        <!-- VIEW 5: LOG AKTIVITAS (Audit Log) (PRD Spec)   -->
        <!-- ============================================== -->
        <div id="subview-log_aktivitas" class="hidden space-y-5">
          <div class="${cardClass} rounded-2xl border p-5">
            <div class="flex items-center justify-between">
              <div>
                <h3 class="text-base font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'}">Audit Trail & Log Aktivitas</h3>
                <p class="text-xs text-slate-400 mt-0.5">Catatan seluruh transaksi dan perubahan data secara real-time</p>
              </div>
              <button onclick="loadLogsTable()" class="px-3 py-1.5 ${isLightTheme ? 'bg-slate-100 text-slate-700' : 'bg-slate-800 text-slate-300'} rounded-xl text-xs font-semibold">
                <i class="fa-solid fa-rotate-right"></i> Refresh Log
              </button>
            </div>
          </div>

          <div class="${cardClass} rounded-2xl border overflow-hidden">
            <div class="overflow-x-auto min-h-[300px]">
              <table class="w-full text-left border-collapse">
                <thead>
                  <tr class="border-b ${isLightTheme ? 'border-slate-200 bg-slate-50 text-slate-600' : 'border-slate-800 bg-slate-900/60 text-slate-400'} text-[11px] font-semibold uppercase tracking-wider">
                    <th class="py-3 px-4">Waktu (Timestamp)</th>
                    <th class="py-3 px-4">User</th>
                    <th class="py-3 px-4">Aksi / Detail Aktivitas</th>
                  </tr>
                </thead>
                <tbody id="logs-full-tbody" class="divide-y ${isLightTheme ? 'divide-slate-100 text-slate-700' : 'divide-slate-800/60 text-slate-200'} text-xs"></tbody>
              </table>
            </div>
          </div>
        </div>

      </main>

      <!-- APP FOOTER -->
      <footer class="border-t ${isLightTheme ? 'border-slate-200 bg-white' : 'border-slate-800/80 bg-slate-950/60'} py-4 px-6 mt-auto">
        <div class="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between text-xs text-slate-400 gap-2">
          <p>© 2026 ${appNameEscaped}. Enterprise Solution on Google Apps Script.</p>
          <div class="flex items-center space-x-4">
            <span class="flex items-center gap-1.5 text-blue-600 font-medium text-[11px]">
              <span class="w-1.5 h-1.5 rounded-full bg-blue-600"></span> Multi-Role Connected
            </span>
          </div>
        </div>
      </footer>
    </div>
  </div>

  <!-- DYNAMIC RECORD MODAL (CREATE / EDIT) -->
  <div id="record-modal" class="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-4 hidden">
    <div class="${cardClass} rounded-2xl border w-full max-w-lg p-6 space-y-5 shadow-2xl relative max-h-[90vh] flex flex-col">
      <div class="flex items-center justify-between border-b ${isLightTheme ? 'border-slate-100' : 'border-slate-800'} pb-3">
        <div>
          <h3 id="record-modal-title" class="text-sm font-bold ${isLightTheme ? 'text-slate-900' : 'text-white'} flex items-center gap-2">
            <i class="fa-solid fa-pen-to-square text-blue-600"></i> <span>Tambah Data</span>
          </h3>
          <p id="record-modal-subtitle" class="text-[11px] text-slate-400">Tabel: <strong id="modal-target-table-name">Data_Utama</strong></p>
        </div>
        <button onclick="closeRecordModal()" class="text-slate-400 hover:text-slate-600 transition text-lg">&times;</button>
      </div>

      <form id="dynamic-record-form" onsubmit="handleRecordSubmit(event)" class="space-y-4 overflow-y-auto pr-1 flex-1 custom-scrollbar">
        <div id="modal-form-fields" class="space-y-3.5"></div>

        <div class="flex items-center justify-end space-x-3 pt-3 border-t ${isLightTheme ? 'border-slate-100' : 'border-slate-800'}">
          <button type="button" onclick="closeRecordModal()" class="px-4 py-2 ${isLightTheme ? 'bg-slate-100 hover:bg-slate-200 text-slate-700' : 'bg-slate-800 hover:bg-slate-700 text-slate-300'} rounded-xl text-xs font-medium transition">Batal</button>
          <button type="submit" id="btn-save-record" class="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl text-xs shadow-lg shadow-blue-500/20 transition flex items-center gap-2">
            <span>Simpan Data</span>
          </button>
        </div>
      </form>
    </div>
  </div>

  <div id="toast-container" class="fixed bottom-6 right-6 z-50 space-y-2"></div>

  <!-- JAVASCRIPT ENTERPRISE LOGIC -->
  <script>
    const SCHEMA = ${schemaJson};
    const HAS_AUTH = ${hasLoginView ? 'true' : 'false'};

    let currentView = 'dashboard';
    let currentDataUtama = [];
    let currentUsers = [];
    let currentLogs = [];
    let currentUser = { username: 'admin', name: 'Administrator Utama', role: 'Admin' };
    let isEditingMode = false;
    let editingRowId = null;
    let activeModalTable = 'Data_Utama';
    let categoryChart = null;
    let trendChart = null;

    document.addEventListener('DOMContentLoaded', () => {
      const savedUser = localStorage.getItem('gas_app_user');
      if (savedUser) {
        try { currentUser = JSON.parse(savedUser); } catch(e) {}
      }

      if (HAS_AUTH && !savedUser) {
        document.getElementById('view-login')?.classList.remove('hidden');
        document.getElementById('view-dashboard-shell')?.classList.add('hidden');
      } else {
        updateUserUI(currentUser);
        document.getElementById('view-login')?.classList.add('hidden');
        document.getElementById('view-dashboard-shell')?.classList.remove('hidden');
        loadDashboard();
      }
    });

    function toggleSidebar() {
      const sidebar = document.getElementById('app-sidebar');
      if (sidebar) sidebar.classList.toggle('hidden');
    }

    function toggleProfileDropdown() {
      const dd = document.getElementById('profile-dropdown');
      if (dd) dd.classList.toggle('hidden');
    }

    document.addEventListener('click', (e) => {
      const btn = document.getElementById('btn-profile-dropdown');
      const dd = document.getElementById('profile-dropdown');
      if (dd && btn && !btn.contains(e.target) && !dd.contains(e.target)) {
        dd.classList.add('hidden');
      }
    });

    function switchView(viewName) {
      currentView = viewName;
      
      document.querySelectorAll('.sidebar-nav-btn').forEach(btn => {
        btn.classList.remove('active', 'bg-blue-500/10', 'text-blue-600', 'border', 'border-blue-500/20');
        btn.classList.add('text-slate-500');
      });

      const dashSub = document.getElementById('subview-dashboard');
      const dataSub = document.getElementById('subview-data_utama');
      const userSub = document.getElementById('subview-manajemen_user');
      const logSub = document.getElementById('subview-log_aktivitas');
      const addBtn = document.getElementById('btn-topbar-add');
      const addLabel = document.getElementById('btn-topbar-add-label');

      [dashSub, dataSub, userSub, logSub].forEach(el => el && el.classList.add('hidden'));
      if (addBtn) addBtn.classList.add('hidden');

      const btnActive = document.getElementById('nav-' + viewName);
      if (btnActive) {
        btnActive.classList.add('active', 'bg-blue-500/10', 'text-blue-600', 'border', 'border-blue-500/20');
        btnActive.classList.remove('text-slate-500');
      }

      if (viewName === 'dashboard') {
        if (dashSub) dashSub.classList.remove('hidden');
        document.getElementById('topbar-page-title').innerText = 'Dashboard Utama';
        document.getElementById('topbar-page-subtitle').innerText = 'Ringkasan & Metrik Sistem';
        loadDashboard();
      } else if (viewName === 'data_utama') {
        if (dataSub) dataSub.classList.remove('hidden');
        if (addBtn) {
          addBtn.classList.remove('hidden');
          addLabel.innerText = 'Tambah Data';
        }
        document.getElementById('topbar-page-title').innerText = 'Tabel Data Utama & Tracker';
        document.getElementById('topbar-page-subtitle').innerText = 'Manajemen Entri Data Real-time';
        loadDataUtamaTable();
      } else if (viewName === 'manajemen_user') {
        if (userSub) userSub.classList.remove('hidden');
        if (addBtn) {
          addBtn.classList.remove('hidden');
          addLabel.innerText = 'Tambah User';
        }
        document.getElementById('topbar-page-title').innerText = 'Manajemen User (Admin)';
        document.getElementById('topbar-page-subtitle').innerText = 'Pengaturan Hak Akses & Akun';
        loadUsersTable();
      } else if (viewName === 'log_aktivitas') {
        if (logSub) logSub.classList.remove('hidden');
        document.getElementById('topbar-page-title').innerText = 'Audit Log Aktivitas';
        document.getElementById('topbar-page-subtitle').innerText = 'Riwayat Transaksi Sistem';
        loadLogsTable();
      }

      if (window.innerWidth < 768) {
        const sb = document.getElementById('app-sidebar');
        if (sb) sb.classList.add('hidden');
      }
    }

    function reloadCurrentView() {
      if (currentView === 'dashboard') loadDashboard();
      else if (currentView === 'data_utama') loadDataUtamaTable();
      else if (currentView === 'manajemen_user') loadUsersTable();
      else if (currentView === 'log_aktivitas') loadLogsTable();
    }

    function handleLogin(e) {
      e.preventDefault();
      const u = document.getElementById('login-username').value;
      const p = document.getElementById('login-password').value;
      const btn = document.getElementById('btn-login');
      const errBox = document.getElementById('login-error');
      const errText = document.getElementById('login-error-text');

      btn.disabled = true;
      btn.innerHTML = '<i class="fa-solid fa-spinner animate-spin"></i> Memvalidasi...';
      if (errBox) errBox.classList.add('hidden');

      if (typeof google !== 'undefined' && google.script && google.script.run) {
        google.script.run
          .withSuccessHandler(res => {
            btn.disabled = false;
            btn.innerHTML = '<span>Masuk ke Sistem</span> <i class="fa-solid fa-arrow-right"></i>';
            if (res.success) {
              currentUser = res.user;
              localStorage.setItem('gas_app_user', JSON.stringify(res.user));
              updateUserUI(res.user);
              document.getElementById('view-login')?.classList.add('hidden');
              document.getElementById('view-dashboard-shell')?.classList.remove('hidden');
              showToast('Selamat datang, ' + (res.user.name || res.user.username) + '!');
              switchView('dashboard');
            } else {
              if (errBox) {
                errText.innerText = res.error || 'Username atau password salah';
                errBox.classList.remove('hidden');
              }
            }
          })
          .withFailureHandler(err => {
            btn.disabled = false;
            btn.innerHTML = '<span>Masuk ke Sistem</span> <i class="fa-solid fa-arrow-right"></i>';
            if (errBox) {
              errText.innerText = err.message || err.toString();
              errBox.classList.remove('hidden');
            }
          })
          .loginUser(u, p);
      } else {
        setTimeout(() => {
          btn.disabled = false;
          btn.innerHTML = '<span>Masuk ke Sistem</span> <i class="fa-solid fa-arrow-right"></i>';
          if ((u === 'admin' && p === 'admin123') || (u === 'budi' && p === 'budi123')) {
            const role = u === 'admin' ? 'Admin' : 'User';
            currentUser = { username: u, name: u === 'admin' ? 'Administrator Utama' : 'Budi Santoso', role: role };
            localStorage.setItem('gas_app_user', JSON.stringify(currentUser));
            updateUserUI(currentUser);
            document.getElementById('view-login')?.classList.add('hidden');
            document.getElementById('view-dashboard-shell')?.classList.remove('hidden');
            showToast('Login berhasil sebagai ' + role + '! (Preview Mode)');
            switchView('dashboard');
          } else {
            if (errBox) {
              errText.innerText = 'Username atau password salah (Demo: admin / admin123)';
              errBox.classList.remove('hidden');
            }
          }
        }, 500);
      }
    }

    function updateUserUI(user) {
      if (!user) return;
      const initial = (user.name || user.username || 'A').charAt(0).toUpperCase();
      const name = user.name || user.username;
      
      ['sidebar-user-initial', 'topbar-user-initial'].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.innerText = initial;
      });
      ['sidebar-user-name', 'topbar-user-name', 'dropdown-user-name'].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.innerText = name;
      });
      ['sidebar-user-role', 'dropdown-user-role'].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.innerText = 'Role: ' + (user.role || 'User');
      });

      // Show/hide admin-only sections based on role
      const adminSection = document.getElementById('sidebar-admin-section');
      if (adminSection) {
        if (user.role === 'Admin') adminSection.classList.remove('hidden');
        else adminSection.classList.add('hidden');
      }
    }

    function handleLogout() {
      localStorage.removeItem('gas_app_user');
      currentUser = null;
      document.getElementById('view-dashboard-shell')?.classList.add('hidden');
      document.getElementById('view-login')?.classList.remove('hidden');
      showToast('Anda telah logout dari sistem.');
    }

    // ==========================================
    // DASHBOARD & CHARTS LOGIC
    // ==========================================
    function loadDashboard() {
      const refreshIcon = document.getElementById('refresh-icon');
      if (refreshIcon) refreshIcon.classList.add('animate-spin');

      if (typeof google !== 'undefined' && google.script && google.script.run) {
        google.script.run
          .withSuccessHandler(renderDashboard)
          .withFailureHandler(err => {
            if (refreshIcon) refreshIcon.classList.remove('animate-spin');
            showToast(err.message, 'error');
          })
          .getDashboardStats();
      } else {
        setTimeout(() => {
          renderDashboard({
            success: true,
            stats: { Data_Utama: 3, Users: 2, Log_Aktivitas: 5 },
            statusCounts: { pending: 1, in_progress: 1, approved: 1, rejected: 0, total: 3 },
            categoryCounts: { 'Software & Tools': 1, 'Hardware & Server': 1, 'Security & Network': 1 },
            recentLogs: [
              { timestamp: '2026-09-12 13:00', username: 'admin', action: 'Login ke sistem (Admin)' },
              { timestamp: '2026-09-12 11:30', username: 'budi', action: 'Menambah permohonan hardware' },
              { timestamp: '2026-09-12 10:15', username: 'admin', action: 'Menyetujui lisensi software tim dev' }
            ],
            spreadsheetUrl: '#'
          });
        }, 400);
      }
    }

    function renderDashboard(res) {
      const refreshIcon = document.getElementById('refresh-icon');
      if (refreshIcon) refreshIcon.classList.remove('animate-spin');

      if (!res.success) return;

      if (res.spreadsheetUrl) {
        const sbLink = document.getElementById('sidebar-sheet-link');
        if (sbLink) sbLink.href = res.spreadsheetUrl;
      }

      const badge = document.getElementById('sidebar-badge-data-utama');
      if (badge) badge.innerText = res.stats?.Data_Utama || 0;

      const sc = res.statusCounts || {};
      document.getElementById('stat-total-records').innerText = sc.total || 0;
      document.getElementById('stat-pending-records').innerText = sc.pending || 0;
      document.getElementById('stat-approved-records').innerText = sc.approved || 0;
      document.getElementById('stat-total-users').innerText = res.stats?.Users || 2;

      // Render Category Chart (Doughnut)
      const catLabels = Object.keys(res.categoryCounts || {});
      const catData = Object.values(res.categoryCounts || {});
      const ctxCat = document.getElementById('chartCategoryCanvas');
      if (ctxCat) {
        if (categoryChart) categoryChart.destroy();
        categoryChart = new Chart(ctxCat, {
          type: 'doughnut',
          data: {
            labels: catLabels.length > 0 ? catLabels : ['Software', 'Hardware', 'Security'],
            datasets: [{
              data: catData.length > 0 ? catData : [1, 1, 1],
              backgroundColor: ['#3b82f6', '#06b6d4', '#10b981', '#f59e0b']
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: { legend: { position: 'bottom', labels: { boxWidth: 10, font: { size: 10 } } } }
          }
        });
      }

      // Render Trend Chart (Bar)
      const ctxTrend = document.getElementById('chartTrendCanvas');
      if (ctxTrend) {
        if (trendChart) trendChart.destroy();
        trendChart = new Chart(ctxTrend, {
          type: 'bar',
          data: {
            labels: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
            datasets: [
              { label: 'Entri Masuk', data: [3, 5, 4, 6, 5, 2, 1], backgroundColor: '#3b82f6', borderRadius: 6 },
              { label: 'Disetujui', data: [2, 4, 3, 5, 4, 2, 1], backgroundColor: '#10b981', borderRadius: 6 }
            ]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: { y: { beginAtZero: true } },
            plugins: { legend: { position: 'bottom', labels: { boxWidth: 10, font: { size: 10 } } } }
          }
        });
      }

      // Render Recent Logs Feed
      const tbody = document.getElementById('recent-logs-tbody');
      if (tbody) {
        const logs = res.recentLogs || [];
        if (logs.length === 0) {
          tbody.innerHTML = '<tr><td colspan="3" class="text-center py-4 text-slate-400">Belum ada aktivitas</td></tr>';
        } else {
          tbody.innerHTML = logs.map(l => \`
            <tr class="hover:bg-blue-50/40 transition">
              <td class="py-2.5 px-3 font-mono text-[11px] text-slate-400">\${l.timestamp}</td>
              <td class="py-2.5 px-3 font-semibold text-blue-600">\${l.username}</td>
              <td class="py-2.5 px-3">\${l.action}</td>
            </tr>
          \`).join('');
        }
      }
    }

    // ==========================================
    // DATA_UTAMA (TRACKER) TABLE LOGIC
    // ==========================================
    function loadDataUtamaTable() {
      if (typeof google !== 'undefined' && google.script && google.script.run) {
        google.script.run
          .withSuccessHandler(res => {
            currentDataUtama = res.rows || [];
            renderDataUtamaRows(currentDataUtama);
          })
          .getTableData('Data_Utama');
      } else {
        currentDataUtama = [
          { ID: 'DAT-001', Tanggal: '2026-09-12 10:15', Nama: 'Permohonan Lisensi Software Tim Dev', Kategori: 'Software & Tools', Status: 'Approved', Catatan: 'Lisensi IDE telah disetujui untuk 5 developer' },
          { ID: 'DAT-002', Tanggal: '2026-09-12 11:30', Nama: 'Pengadaan Hardware Server Backup', Kategori: 'Hardware & Server', Status: 'In Progress', Catatan: 'Sedang proses verifikasi vendor penyedia' },
          { ID: 'DAT-003', Tanggal: '2026-09-12 13:00', Nama: 'Audit Keamanan Jaringan Kantor Pusat', Kategori: 'Security & Network', Status: 'Pending', Catatan: 'Menunggu persetujuan jadwal audit dari IT Security' }
        ];
        renderDataUtamaRows(currentDataUtama);
      }
    }

    function renderDataUtamaRows(rows) {
      const tbody = document.getElementById('data_utama-tbody');
      const badge = document.getElementById('data_utama-count-badge');
      if (badge) badge.innerText = rows.length + ' Baris';
      if (!tbody) return;

      if (rows.length === 0) {
        tbody.innerHTML = '<tr><td colspan="7" class="text-center py-8 text-slate-400">Tidak ada data ditemukan</td></tr>';
        return;
      }

      tbody.innerHTML = rows.map(row => {
        const encoded = encodeURIComponent(JSON.stringify(row));
        return \`
        <tr class="hover:bg-blue-50/40 transition">
          <td class="py-3 px-4 font-mono font-bold text-blue-600">\${row.ID || '-'}</td>
          <td class="py-3 px-4 text-slate-400 whitespace-nowrap">\${row.Tanggal || '-'}</td>
          <td class="py-3 px-4 font-semibold \${'${isLightTheme ? 'text-slate-800' : 'text-slate-200'}'}">\${row.Nama || '-'}</td>
          <td class="py-3 px-4">\${row.Kategori || '-'}</td>
          <td class="py-3 px-4">\${formatStatusPill(row.Status)}</td>
          <td class="py-3 px-4 text-slate-500 max-w-xs truncate">\${row.Catatan || '-'}</td>
          <td class="py-3 px-4 text-right">
            <div class="flex items-center justify-end space-x-1.5">
              <button onclick="openEditModal('Data_Utama', '\${encoded}')" title="Edit Data" class="p-1.5 rounded-lg ${isLightTheme ? 'bg-slate-100 hover:bg-slate-200 text-blue-600' : 'bg-slate-800 text-cyan-400'}">
                <i class="fa-solid fa-pen text-xs"></i>
              </button>
              <button onclick="confirmDeleteRow('Data_Utama', '\${row.ID}')" title="Hapus Data" class="p-1.5 rounded-lg ${isLightTheme ? 'bg-slate-100 hover:bg-rose-100 text-rose-600' : 'bg-slate-800 text-rose-400'}">
                <i class="fa-solid fa-trash text-xs"></i>
              </button>
            </div>
          </td>
        </tr>\`;
      }).join('');
    }

    function filterDataUtamaTable() {
      const q = (document.getElementById('data_utama-search')?.value || '').toLowerCase();
      const status = document.getElementById('data_utama-filter-status')?.value || 'ALL';

      const filtered = currentDataUtama.filter(r => {
        const matchesQ = (r.Nama || '').toLowerCase().includes(q) || (r.ID || '').toLowerCase().includes(q) || (r.Catatan || '').toLowerCase().includes(q);
        const matchesStatus = status === 'ALL' || String(r.Status || '').toLowerCase() === status.toLowerCase();
        return matchesQ && matchesStatus;
      });

      renderDataUtamaRows(filtered);
    }

    // ==========================================
    // USERS (MANAJEMEN USER) TABLE LOGIC
    // ==========================================
    function loadUsersTable() {
      if (typeof google !== 'undefined' && google.script && google.script.run) {
        google.script.run
          .withSuccessHandler(res => {
            currentUsers = res.rows || [];
            renderUsersRows(currentUsers);
          })
          .getTableData('Users');
      } else {
        currentUsers = [
          { ID: 'USR-001', Username: 'admin', Password: '••••••', NamaLengkap: 'Administrator Utama', Email: 'admin@company.com', Role: 'Admin', Status: 'Active', LastLogin: '2026-09-12 10:00:00' },
          { ID: 'USR-002', Username: 'budi', Password: '••••••', NamaLengkap: 'Budi Santoso', Email: 'budi@company.com', Role: 'User', Status: 'Active', LastLogin: '2026-09-12 09:30:00' }
        ];
        renderUsersRows(currentUsers);
      }
    }

    function renderUsersRows(rows) {
      const tbody = document.getElementById('users-tbody');
      if (!tbody) return;

      tbody.innerHTML = rows.map(u => {
        const encoded = encodeURIComponent(JSON.stringify(u));
        const isAdmin = u.Role === 'Admin';
        return \`
        <tr class="hover:bg-blue-50/40 transition">
          <td class="py-3 px-4 font-mono font-bold text-slate-500">\${u.ID || '-'}</td>
          <td class="py-3 px-4 font-semibold text-blue-600">\${u.Username}</td>
          <td class="py-3 px-4 font-bold \${'${isLightTheme ? 'text-slate-800' : 'text-slate-200'}'}">\${u.NamaLengkap || '-'}</td>
          <td class="py-3 px-4 text-slate-400">\${u.Email || '-'}</td>
          <td class="py-3 px-4">
            <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold \${isAdmin ? 'bg-indigo-500/10 text-indigo-600 border border-indigo-500/20' : 'bg-slate-500/10 text-slate-600 border border-slate-500/20'}">
              \${u.Role}
            </span>
          </td>
          <td class="py-3 px-4">
            <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold \${u.Status === 'Active' ? 'bg-emerald-500/10 text-emerald-600 border border-emerald-500/20' : 'bg-rose-500/10 text-rose-600 border border-rose-500/20'}">
              \${u.Status}
            </span>
          </td>
          <td class="py-3 px-4 text-[11px] text-slate-400 font-mono">\${u.LastLogin || '-'}</td>
          <td class="py-3 px-4 text-right">
            <div class="flex items-center justify-end space-x-1.5">
              <button onclick="openEditModal('Users', '\${encoded}')" title="Edit Akun" class="p-1.5 rounded-lg ${isLightTheme ? 'bg-slate-100 hover:bg-slate-200 text-blue-600' : 'bg-slate-800 text-cyan-400'}">
                <i class="fa-solid fa-pen text-xs"></i>
              </button>
              <button onclick="confirmDeleteRow('Users', '\${u.ID}')" title="Hapus Akun" class="p-1.5 rounded-lg ${isLightTheme ? 'bg-slate-100 hover:bg-rose-100 text-rose-600' : 'bg-slate-800 text-rose-400'}">
                <i class="fa-solid fa-trash text-xs"></i>
              </button>
            </div>
          </td>
        </tr>\`;
      }).join('');
    }

    function filterUsersTable() {
      const q = (document.getElementById('users-search')?.value || '').toLowerCase();
      const filtered = currentUsers.filter(u => 
        (u.Username || '').toLowerCase().includes(q) || 
        (u.NamaLengkap || '').toLowerCase().includes(q) || 
        (u.Email || '').toLowerCase().includes(q)
      );
      renderUsersRows(filtered);
    }

    // ==========================================
    // LOG_AKTIVITAS TABLE LOGIC
    // ==========================================
    function loadLogsTable() {
      if (typeof google !== 'undefined' && google.script && google.script.run) {
        google.script.run
          .withSuccessHandler(res => renderLogsRows(res.rows || []))
          .getTableData('Log_Aktivitas');
      } else {
        renderLogsRows([
          { Timestamp: '2026-09-12 13:00:15', Username: 'admin', Aksi: 'Login ke sistem (Admin)' },
          { Timestamp: '2026-09-12 11:30:20', Username: 'budi', Aksi: 'Menambah data baru di tabel Data_Utama (DAT-002)' },
          { Timestamp: '2026-09-12 10:15:45', Username: 'admin', Aksi: 'Memperbarui data di Data_Utama (DAT-001)' }
        ]);
      }
    }

    function renderLogsRows(rows) {
      const tbody = document.getElementById('logs-full-tbody');
      if (!tbody) return;
      tbody.innerHTML = rows.map(l => \`
        <tr class="hover:bg-blue-50/40 transition">
          <td class="py-3 px-4 font-mono text-[11px] text-slate-400">\${l.Timestamp || l.timestamp}</td>
          <td class="py-3 px-4 font-bold text-blue-600">\${l.Username || l.username}</td>
          <td class="py-3 px-4 text-slate-700">\${l.Aksi || l.aksi || l.action}</td>
        </tr>
      \`).join('');
    }

    function formatStatusPill(status) {
      if (!status) return '<span class="text-slate-400">-</span>';
      const s = String(status);
      if (s === 'Approved' || s === 'Selesai' || s === 'Active' || s === 'Disetujui') {
        return \`<span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/10 text-emerald-600 border border-emerald-500/20">\${s}</span>\`;
      }
      if (s === 'In Progress' || s === 'Proses') {
        return \`<span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-cyan-500/10 text-cyan-600 border border-cyan-500/20">\${s}</span>\`;
      }
      if (s === 'Pending' || s === 'Review' || s === 'Menunggu') {
        return \`<span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-500/10 text-amber-600 border border-amber-500/20">\${s}</span>\`;
      }
      if (s === 'Rejected' || s === 'Ditolak' || s === 'Inactive') {
        return \`<span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-rose-500/10 text-rose-600 border border-rose-500/20">\${s}</span>\`;
      }
      return s;
    }

    // ==========================================
    // MODAL FORM CRUD LOGIC
    // ==========================================
    function openCreateModalForActiveView() {
      if (currentView === 'manajemen_user') openCreateModal('Users');
      else openCreateModal('Data_Utama');
    }

    function openCreateModal(tableName) {
      isEditingMode = false;
      editingRowId = null;
      activeModalTable = tableName;
      
      const tableDef = SCHEMA.find(s => s.name === tableName) || SCHEMA[0];
      document.getElementById('record-modal-title').innerHTML = '<i class="fa-solid fa-plus text-blue-600"></i> <span>Tambah ' + tableName.replace(/_/g, ' ') + ' Baru</span>';
      document.getElementById('modal-target-table-name').innerText = tableName;

      const container = document.getElementById('modal-form-fields');
      container.innerHTML = generateFormInputs(tableDef.headers, null, tableName);

      document.getElementById('record-modal')?.classList.remove('hidden');
    }

    function openEditModal(tableName, encodedRow) {
      isEditingMode = true;
      activeModalTable = tableName;
      const row = JSON.parse(decodeURIComponent(encodedRow));
      const tableDef = SCHEMA.find(s => s.name === tableName) || SCHEMA[0];
      const idHeader = tableDef.headers.find(h => h.toLowerCase().includes('id') || h.toLowerCase().includes('kode')) || tableDef.headers[0];
      
      editingRowId = row[idHeader];

      document.getElementById('record-modal-title').innerHTML = '<i class="fa-solid fa-pen text-blue-600"></i> <span>Edit ' + tableName.replace(/_/g, ' ') + '</span>';
      document.getElementById('modal-target-table-name').innerText = tableName;

      const container = document.getElementById('modal-form-fields');
      container.innerHTML = generateFormInputs(tableDef.headers, row, tableName);

      document.getElementById('record-modal')?.classList.remove('hidden');
    }

    function closeRecordModal() {
      document.getElementById('record-modal')?.classList.add('hidden');
    }

    function generateFormInputs(headers, initialData = null, tableName = '') {
      return headers.map(h => {
        const hl = h.toLowerCase();
        const isAuto = (hl === 'id' || hl === 'createdat' || hl === 'timestamp' || hl === 'lastlogin') && !initialData;
        const val = initialData && initialData[h] !== undefined ? initialData[h] : '';

        if (isAuto) {
          return \`
          <div>
            <label class="block text-[11px] font-semibold text-slate-400 mb-1">\${h} (Auto Generated)</label>
            <input type="text" name="\${h}" value="(Otomatis)" readonly class="w-full px-3 py-2 rounded-xl text-xs ${inputClass} opacity-60 cursor-not-allowed">
          </div>\`;
        }

        if (hl === 'role') {
          return \`
          <div>
            <label class="block text-[11px] font-semibold ${isLightTheme ? 'text-slate-700' : 'text-slate-300'} mb-1">Role Pengguna *</label>
            <select name="\${h}" class="w-full px-3 py-2 rounded-xl text-xs ${inputClass}">
              <option value="User" \${val === 'User' || !val ? 'selected' : ''}>User (Staff Operasional)</option>
              <option value="Admin" \${val === 'Admin' ? 'selected' : ''}>Admin (Administrator Penuh)</option>
            </select>
          </div>\`;
        }

        if (hl === 'status') {
          const isUser = tableName === 'Users';
          return \`
          <div>
            <label class="block text-[11px] font-semibold ${isLightTheme ? 'text-slate-700' : 'text-slate-300'} mb-1">Status *</label>
            <select name="\${h}" class="w-full px-3 py-2 rounded-xl text-xs ${inputClass}">
              \${isUser ? \`
                <option value="Active" \${val === 'Active' || !val ? 'selected' : ''}>Active</option>
                <option value="Inactive" \${val === 'Inactive' ? 'selected' : ''}>Inactive</option>
              \` : \`
                <option value="Pending" \${val === 'Pending' || !val ? 'selected' : ''}>Pending / Review</option>
                <option value="In Progress" \${val === 'In Progress' ? 'selected' : ''}>In Progress</option>
                <option value="Approved" \${val === 'Approved' ? 'selected' : ''}>Approved / Selesai</option>
                <option value="Rejected" \${val === 'Rejected' ? 'selected' : ''}>Rejected</option>
              \`}
            </select>
          </div>\`;
        }

        if (hl === 'password') {
          return \`
          <div>
            <label class="block text-[11px] font-semibold ${isLightTheme ? 'text-slate-700' : 'text-slate-300'} mb-1">Password *</label>
            <input type="password" name="\${h}" value="\${val}" required placeholder="Masukkan password akun..." class="w-full px-3 py-2 rounded-xl text-xs ${inputClass}">
          </div>\`;
        }

        if (hl.includes('catatan') || hl.includes('keterangan') || hl.includes('deskripsi')) {
          return \`
          <div>
            <label class="block text-[11px] font-semibold ${isLightTheme ? 'text-slate-700' : 'text-slate-300'} mb-1">\${h}</label>
            <textarea name="\${h}" rows="2" placeholder="Masukkan \${h}..." class="w-full px-3 py-2 rounded-xl text-xs ${inputClass}">\${val}</textarea>
          </div>\`;
        }

        return \`
        <div>
          <label class="block text-[11px] font-semibold ${isLightTheme ? 'text-slate-700' : 'text-slate-300'} mb-1">\${h} *</label>
          <input type="text" name="\${h}" value="\${val}" required placeholder="Masukkan \${h}..." class="w-full px-3 py-2 rounded-xl text-xs ${inputClass}">
        </div>\`;
      }).join('');
    }

    function handleRecordSubmit(e) {
      e.preventDefault();
      const form = document.getElementById('dynamic-record-form');
      const formData = new FormData(form);
      const payload = {};
      formData.forEach((value, key) => {
        if (value !== '(Otomatis)') payload[key] = value;
      });

      const btn = document.getElementById('btn-save-record');
      btn.disabled = true;
      btn.innerText = 'Menyimpan...';

      if (typeof google !== 'undefined' && google.script && google.script.run) {
        if (isEditingMode && editingRowId) {
          google.script.run
            .withSuccessHandler(res => {
              btn.disabled = false;
              btn.innerText = 'Simpan Data';
              if (res.success) {
                showToast(res.message);
                closeRecordModal();
                reloadCurrentView();
              } else {
                showToast(res.error, 'error');
              }
            })
            .updateRecord(activeModalTable, editingRowId, payload, currentUser?.username || 'Admin');
        } else {
          google.script.run
            .withSuccessHandler(res => {
              btn.disabled = false;
              btn.innerText = 'Simpan Data';
              if (res.success) {
                showToast(res.message);
                closeRecordModal();
                reloadCurrentView();
              } else {
                showToast(res.error, 'error');
              }
            })
            .createRecord(activeModalTable, payload, currentUser?.username || 'Admin');
        }
      } else {
        setTimeout(() => {
          btn.disabled = false;
          btn.innerText = 'Simpan Data';
          showToast('Data berhasil disimpan! (Preview Mode)');
          closeRecordModal();
          reloadCurrentView();
        }, 400);
      }
    }

    function confirmDeleteRow(tableName, rowId) {
      if (!confirm('Yakin ingin menghapus record ini dari tabel ' + tableName + '?')) return;

      if (typeof google !== 'undefined' && google.script && google.script.run) {
        google.script.run
          .withSuccessHandler(res => {
            if (res.success) {
              showToast(res.message);
              reloadCurrentView();
            } else {
              showToast(res.error, 'error');
            }
          })
          .deleteRecord(tableName, rowId, currentUser?.username || 'Admin');
      } else {
        showToast('Data berhasil dihapus! (Preview Mode)');
        if (tableName === 'Data_Utama') {
          currentDataUtama = currentDataUtama.filter(r => r.ID !== rowId);
          renderDataUtamaRows(currentDataUtama);
        } else if (tableName === 'Users') {
          currentUsers = currentUsers.filter(u => u.ID !== rowId);
          renderUsersRows(currentUsers);
        }
      }
    }

    function exportTableToCSV(tableName) {
      const data = tableName === 'Data_Utama' ? currentDataUtama : currentUsers;
      if (!data || data.length === 0) {
        showToast('Tidak ada data untuk diekspor', 'error');
        return;
      }
      const tableDef = SCHEMA.find(s => s.name === tableName) || SCHEMA[0];
      let csvContent = "data:text/csv;charset=utf-8," + tableDef.headers.join(",") + "\\n";

      data.forEach(row => {
        const rowStr = tableDef.headers.map(h => {
          let cell = String(row[h] || '').replace(/"/g, '""');
          return '"' + cell + '"';
        }).join(",");
        csvContent += rowStr + "\\n";
      });

      const encodedUri = encodeURI(csvContent);
      const link = document.createElement("a");
      link.setAttribute("href", encodedUri);
      link.setAttribute("download", tableName + "_export.csv");
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      showToast('Berhasil mendownload ' + tableName + '.csv');
    }

    function showToast(message, type = 'success') {
      const toast = document.createElement('div');
      const isSuccess = type === 'success';
      toast.className = \`px-4 py-3 rounded-xl shadow-xl flex items-center gap-2.5 text-xs font-semibold text-white transition-all transform duration-300 translate-y-2 opacity-0 \${isSuccess ? 'bg-blue-600 border border-blue-400/30' : 'bg-rose-600 border border-rose-400/30'}\`;
      toast.innerHTML = \`<i class="fa-solid \${isSuccess ? 'fa-circle-check' : 'fa-triangle-exclamation'}"></i> <span>\${message}</span>\`;
      
      const container = document.getElementById('toast-container');
      container.appendChild(toast);
      
      requestAnimationFrame(() => {
        toast.classList.remove('translate-y-2', 'opacity-0');
      });

      setTimeout(() => {
        toast.classList.add('opacity-0', 'translate-y-2');
        setTimeout(() => toast.remove(), 300);
      }, 3500);
    }
  </script>
</body>
</html>`
	};

	return [appsscriptJson, codeGs, setupGs, indexHtml];
}
